source:
  url: 'postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${SOURCE_DATABASE_DB}?sslmode=disable'
  model:
    tables:
      caching_source: &caching_source
        schema: demos
        columns:
          id: integer
          name: string
          surname: string
        keys:
          - id
target:
  url: 'postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${TARGET_DATABASE_DB}?sslmode=disable'
  model:
    tables:
      caching_target:
        <<: *caching_source
        resourceName: ~
        schema: demos
        sourceTable: caching_source
