source:
  url: 'postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}'
  model:
    tables:
      source_table:
        schema: demos
        columns:
          id: integer
          name: string
          surname: string
        keys:
          - id
target:
  url: 'postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}'
  model:
    tables:
      target_table:
        resourceName: ~
        inherit: '@source.tables.source_table'
        sourceTable: source_table
        schema: demos
